# Generated by Django 4.0.6 on 2023-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('middlename', models.TextField()),
                ('lastname', models.TextField()),
                ('dateofbirth', models.DateField()),
            ],
        ),
    ]
